# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, deepseq, hashable, HTF, mtl, QuickCheck, safe, safecopy
, unorderedContainers, vector
}:

cabal.mkDerivation (self: {
  pname = "graph-core";
  version = "0.2.0.1";
  sha256 = "0yi92bgwh365rv3kgcm1xxv6j05k8lpb5hygc20vsfyc8wd958h0";
  buildDepends = [
    deepseq hashable mtl QuickCheck safe safecopy unorderedContainers
    vector
  ];
  testDepends = [
    deepseq hashable HTF mtl QuickCheck safe safecopy
    unorderedContainers vector
  ];
  meta = {
    homepage = "https://github.com/factisresearch/graph-core";
    description = "Fast, memory efficient and persistent graph implementation";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
