# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, hexpat, tagsoup }:

cabal.mkDerivation (self: {
  pname = "hexpat-tagsoup";
  version = "0.1";
  sha256 = "0481446ba5m0h8lxmp216gzll0wr77mhk6hvm087749fwjj597aj";
  buildDepends = [ hexpat tagsoup ];
  meta = {
    description = "Parse (possibly malformed) HTML to hexpat tree";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
