# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, deepseq, hexpat, hexpatTagsoup, lens }:

cabal.mkDerivation (self: {
  pname = "hexpat-lens";
  version = "0.1.2";
  sha256 = "1k4ixqwpsa4mnywd1fcfrmy2dbcpkna0hg0sxjlfp0qbhy1ik7v7";
  buildDepends = [ deepseq hexpat hexpatTagsoup lens ];
  meta = {
    description = "Lenses for Hexpat";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
