# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, transformers }:

cabal.mkDerivation (self: {
  pname = "monad-st";
  version = "0.2.4";
  sha256 = "1j67s07p5lsr81cjl0ch5d1q7zarmpak5kmnwckhavihg3l5m3bi";
  buildDepends = [ transformers ];
  meta = {
    homepage = "http://github.com/ekmett/monad-st";
    description = "Provides a MonadST class";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
