# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, base64Bytestring, blazeHtml, caseInsensitive
, digestiveFunctors, hashable, hspec2, hspecWai, httpTypes
, monadControl, mtl, pathPieces, random, reroute, resourcePool
, resourcet, stm, text, time, transformers, transformersBase
, unorderedContainers, vault, wai, waiExtra, warp
}:

cabal.mkDerivation (self: {
  pname = "Spock";
  version = "0.7.4.0";
  sha256 = "08radcr4c045l2nzff7ly6b0bhmb70wix1q1ws2wf3d8p2kimpir";
  buildDepends = [
    aeson base64Bytestring blazeHtml caseInsensitive digestiveFunctors
    hashable httpTypes monadControl mtl pathPieces random reroute
    resourcePool resourcet stm text time transformers transformersBase
    unorderedContainers vault wai waiExtra warp
  ];
  testDepends = [ hspec2 hspecWai text wai ];
  meta = {
    homepage = "https://github.com/agrafix/Spock";
    description = "Another Haskell web framework for rapid development";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
