# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, either, kanExtensions, monadControl, mtl, profunctors
, transformers, transformersBase
}:

cabal.mkDerivation (self: {
  pname = "trace";
  version = "0.1.0.3";
  sha256 = "0aj83yx8y556kvax775bjbjscyj9fq0rk0rbqcki4ivxzv5x2wvh";
  buildDepends = [
    either kanExtensions monadControl mtl profunctors transformers
    transformersBase
  ];
  meta = {
    description = "A monad transformer for tracing provenience of errors";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
